In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [70]:
df = pd.read_csv('Data/sonar data.csv')
df.sample(5)


0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
123  0.0388  0.0324  0.0688  0.0898  0.1267  0.1515  0.2134  0.2613  0.2832   
138  0.0164  0.0627  0.0738  0.0608  0.0233  0.1048  0.1338  0.0644  0.1522   
117  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   
162  0.0072  0.0027  0.0089  0.0061  0.0420  0.0865  0.1182  0.0999  0.1976   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
123  0.2718  ...  0.0255  0.0071  0.0263  0.0079  0.0111  0.0107  0.0068   
138  0.0780  ...  0.0258  0.0143  0.0226  0.0187  0.0185  0.0110  0.0094   
117  0.1444  ...  0.0115  0.0190  0.0055  0.0096  0.0050  0.0066  0.0114   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   
162  0.2318  ...  0.0078  0.0071  0.0081  0.0034  0.0064  0.0037  0.0036   

     0.0090  0.0032  R  
123  0.0097  0.0067  M  
138  0.0078  0.0112  M  
117  0.0073  0.0033  M  
206  0.0061  0.0115  M  
162  0.0012  0.0037  M  

[5 rows x 61 columns]

In [71]:
df.sample(5).values


array([[0.0201, 0.0026, 0.0138, 0.0062, 0.0133, 0.0151, 0.0541, 0.021,
        0.0505, 0.1097, 0.0841, 0.0942, 0.1204, 0.042, 0.0031, 0.0162,
        0.0624, 0.2127, 0.3436, 0.3813, 0.3825, 0.4764, 0.6313, 0.7523,
        0.8675, 0.8788, 0.7901, 0.8357, 0.9631, 0.9619, 0.9236, 0.8903,
        0.9708, 0.9647, 0.7892, 0.5307, 0.2718, 0.1953, 0.1374, 0.3105,
        0.379, 0.4105, 0.3355, 0.2998, 0.2748, 0.2024, 0.1043, 0.0453,
        0.0337, 0.0122, 0.0072, 0.0108, 0.007, 0.0063, 0.003, 0.0011,
        0.0007, 0.0024, 0.0057, 0.0044, 'R'],
       [0.0071, 0.0103, 0.0135, 0.0494, 0.0253, 0.0806, 0.0701, 0.0738,
        0.0117, 0.0898, 0.0289, 0.1554, 0.1437, 0.1035, 0.1424, 0.1227,
        0.0892, 0.2047, 0.0827, 0.1524, 0.3031, 0.1608, 0.0667, 0.1426,
        0.0395, 0.1653, 0.3399, 0.4855, 0.5206, 0.5508, 0.6102, 0.5989,
        0.6764, 0.8897, 1.0, 0.9517, 0.8459, 0.7073, 0.6697, 0.6326,
        0.5102, 0.4161, 0.2816, 0.1705, 0.1421, 0.0971, 0.0879, 0.0863,
        0.0355, 0.0233, 0.

In [34]:
df.duplicated().sum()


0

In [35]:
df.shape


(207, 61)

In [36]:
cname = [i for i in range(0, 60)]


In [37]:
cname.append('Label')


In [38]:
df.columns = cname


In [39]:
x = df.iloc[:, :60]
y = df.iloc[:, -1]


In [40]:
y = np.array(y.replace({'R': 0, 'M': 1}))


In [41]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
from sklearn.model_selection import train_test_split
knn = KNeighborsClassifier(n_neighbors=5, p=2)


In [42]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.1, random_state=2)


In [43]:
p = knn.fit(x_train, y_train)
y_pred = p.predict(x_test)


In [44]:
print(y_pred)


[1 1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 1 0 1 0]


In [45]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(precision_score(y_test, y_pred))


0.9523809523809523
[[ 8  1]
 [ 0 12]]
0.9230769230769231


In [85]:
inp = [[0.0201, 0.0026, 0.0138, 0.0062, 0.0133, 0.0151, 0.0541, 0.021,
        0.0505, 0.1097, 0.0841, 0.0942, 0.1204, 0.042, 0.0031, 0.0162,
        0.0624, 0.2127, 0.3436, 0.3813, 0.3825, 0.4764, 0.6313, 0.7523,
        0.8675, 0.8788, 0.7901, 0.8357, 0.9631, 0.9619, 0.9236, 0.8903,
        0.9708, 0.9647, 0.7892, 0.5307, 0.2718, 0.1953, 0.1374, 0.3105,
        0.379, 0.4105, 0.3355, 0.2998, 0.2748, 0.2024, 0.1043, 0.0453,
        0.0337, 0.0122, 0.0072, 0.0108, 0.007, 0.0063, 0.003, 0.0011,
        0.0007, 0.0024, 0.0057, 0.0044],
       [0.0131, 0.0387, 0.0329, 0.0078, 0.0721, 0.1341, 0.1626, 0.1902,
        0.261, 0.3193, 0.3468, 0.3738, 0.3055, 0.1926, 0.1385, 0.2122,
        0.2758, 0.4576, 0.6487, 0.7154, 0.801, 0.7924, 0.8793, 1.0,
        0.9865, 0.9474, 0.9474, 0.9315, 0.8326, 0.6213, 0.3772, 0.2822,
        0.2042, 0.219, 0.2223, 0.1327, 0.0521, 0.0618, 0.1416, 0.146,
        0.0846, 0.1055, 0.1639, 0.1916, 0.2085, 0.2335, 0.1964, 0.13,
        0.0633, 0.0183, 0.0137, 0.015, 0.0076, 0.0032, 0.0037, 0.0071,
        0.004, 0.0009, 0.0015, 0.0085]]
pre = p.predict(inp)
for i in pre:
    if i == 0:
        print("Rock")
    else:
        print("Mine")


Rock
Mine
